import { SiteConfig } from "@/types/config.types";

export const siteConfig: SiteConfig = {
  business: {
    name: "Apex Gym",
    tagline: "Train Hard. Become Unstoppable.",
    logo: "/images/logo.png",
  },
  theme: {
    primary: "#00FF85", // Neon Green
    secondary: "#00cc6a", // Dim Neon
  },
  contact: {
    phone: "+91 7303224509",
    email: "alisadik99@gmail.com",
    whatsapp: "+917303224509",
    address: "501 KSA Heights, 2nd Sankli Street, Byculla west 400008",
    googleMapLink: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3305.738872016599!2d-118.44524858478496!3d34.05063078060591!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2bc047e29b7df%3A0x915c6c06df9a1841!2sSanta%20Monica%20Blvd%2C%20Los%20Angeles%2C%20CA!5e0!3m2!1sen!2sus!4v1655000000000!5m2!1sen!2sus",
    businessHours: "Standard Gym Access (5 AM - 10 PM)",
  },
  socialLinks: {
    facebook: "https://facebook.com",
    instagram: "https://instagram.com",
    twitter: "https://twitter.com",
    youtube: "https://youtube.com",
  },
  seo: {
    title: "Apex Gym | Train Hard. Become Unstoppable.",
    description: "Experience premium, state-of-the-art training facilities, elite level trainers, and high-performance membership plans at Apex Gym. Push your limits today.",
    keywords: ["gym", "fitness", "personal training", "elite coaches", "luxury fitness", "weight training", "cardio", "fat loss", "Apex Gym"],
    ogImage: "/images/og-image.jpg",
  },
  hero: {
    badge: "Apex Luxury Fitness Club",
    headingLine1: "Train Hard.",
    headingLine2: "Become ",
    highlightedWord: "Unstoppable",
    subheading: "Premium fitness experience designed to push your limits. Unlock your true physical potential with elite coaching and state-of-the-art facilities.",
    primaryButtonText: "Join Now",
    secondaryButtonText: "View Plans",
    backgroundImage: "/images/hero-bg.png",
  },
  programs: [
    {
      id: "strength",
      title: "Strength Training",
      description: "Build robust muscle mass, density, and power with elite weightlifting routines and custom-tailored progressive overload plans.",
      icon: "Dumbbell",
    },
    {
      id: "fatloss",
      title: "Fat Loss",
      description: "Torch calories, spike your metabolic rate, and uncover a defined, shredded physique using advanced fat-burning protocols.",
      icon: "Flame",
    },
    {
      id: "cardio",
      title: "Cardio & Endurance",
      description: "Supercharge your cardiovascular system, boost stamina, and scale your heart health using advanced aerobic training models.",
      icon: "HeartPulse",
    },
    {
      id: "personal",
      title: "Personal Training",
      description: "Accelerate your results with a highly customized 1-on-1 coaching program, tailored specific to your lifestyle, body type, and goals.",
      icon: "Target",
    },
  ],
  trainers: [
    {
      id: "marcus-vance",
      name: "Marcus Vance",
      role: "Strength & Conditioning Coach",
      image: "/images/trainer-1.png",
      instagram: "https://instagram.com",
      twitter: "https://twitter.com",
    },
    {
      id: "elena-rostova",
      name: "Elena Rostova",
      role: "HIIT & Fat Loss Specialist",
      image: "/images/trainer-2.png",
      instagram: "https://instagram.com",
      twitter: "https://twitter.com",
    },
    {
      id: "darian-cole",
      name: "Darian Cole",
      role: "Calisthenics & Mobility expert",
      image: "/images/trainer-3.png",
      instagram: "https://instagram.com",
      twitter: "https://twitter.com",
    },
  ],
  pricing: [
    {
      id: "basic",
      name: "Basic Plan",
      price: "29",
      duration: "month",
      isPopular: false,
      features: [
        { text: "Standard Gym Access (5 AM - 10 PM)", included: true },
        { text: "Basic Locker Room Access", included: true },
        { text: "Full Strength & Cardio Area Access", included: true },
        { text: "Free High-speed Gym Wi-Fi", included: true },
        { text: "1x Fitness Orientation Session", included: true },
      ],
    },
    {
      id: "pro",
      name: "Pro Performance",
      price: "59",
      duration: "month",
      isPopular: true,
      features: [
        { text: "Full 24/7 Gym Access", included: true },
        { text: "Access to All Group Classes", included: true },
        { text: "2x 1-on-1 Personal Training/mo", included: true },
        { text: "Custom Digital Workout App Access", included: true },
        { text: "Tailored Nutritional Meal Plans", included: true },
        { text: "Premium Locker & Sauna Access", included: true },
      ],
    },
    {
      id: "elite",
      name: "Elite Prestige",
      price: "99",
      duration: "month",
      isPopular: false,
      features: [
        { text: "Full 24/7 Gym Access", included: true },
        { text: "Unlimited 1-on-1 Elite Coaching", included: true },
        { text: "All Pro Features Included", included: true },
        { text: "Weekly Body Composition Analytics", included: true },
        { text: "Complimentary Sports Massages", included: true },
        { text: "Exclusive Apex VIP Lounge Access", included: true },
      ],
    },
  ],
  testimonials: [
    {
      id: "1",
      name: "Sarah Jenkins",
      role: "Corporate Executive",
      image: "",
      content: "The training philosophy at Apex Gym completely changed my approach to physical health. In just 6 months, I've broken all my personal records, shed 34 lbs of fat, and unlocked a level of energy I didn't think was possible. The coaches are absolute geniuses!",
      rating: 5,
    },
    {
      id: "2",
      name: "John Miller",
      role: "Professional Athlete",
      image: "",
      content: "Apex is a premium athletic club in every sense. The equipment is state-of-the-art, the coaches are exceptionally knowledgeable in sports science, and the environment pushes you to execute at 100%. Hands down the best gym in the country.",
      rating: 5,
    },
    {
      id: "3",
      name: "David Kross",
      role: "Tech Entrepreneur",
      image: "",
      content: "As a founder with a hectic schedule, the 24/7 keycard access and the custom mobile nutrition tracking app are absolute game-changers. I can fit my workouts in at midnight or 5 AM, knowing the facilities are always pristine and secure. A premium experience.",
      rating: 5,
    },
  ],
  transformations: [
    {
      id: "1",
      beforeImage: "/images/transform-1.png",
      afterImage: "/images/transform-1.png",
      clientName: "Sarah Jenkins",
      duration: "6 Months",
    },
    {
      id: "2",
      beforeImage: "/images/transform-2.png",
      afterImage: "/images/transform-2.png",
      clientName: "John Miller",
      duration: "12 Months",
    },
  ],
  cta: {
    headingLine1: "Start Your Fitness",
    headingLine2: "Journey",
    highlightedWord: "Today",
    subheading: "Stop waiting for \"tomorrow\". Take command of your body, build championship physical endurance, and redefine what's possible with Apex.",
    buttonText: "Join Apex Gym",
  },
};
